#!/usr/bin/env bash

attributes=(
  'Model Identifier' 'Processor Name' 'Processor Speed' 'Memory' 'Capacity'
  'Media Name' 'Medium Type' 'Protocol' 'Chipset Model' 'Resolution' ''
)

re_attributes=$(printf "|%s" "${attributes[@]}")

system_profiler SPHardwareDataType SPStorageDataType \
  SPDisplaysDataType -detailLevel mini \
  | grep -E "'$re_attributes'" \
  | sed -e 's/^[[:space:]]*//'

system_profiler SPDisplaysDataType -detailLevel mini \
  | grep -A1 'Displays:'  \
  | tail -n +5 \
  | sed -e 's/^[[:space:]]*//' \
  | sed -e 's/://' \
  | sed -e 's/^/Display: /' \
